/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAcademiaRouteImport } from './routes/_authenticated/academia'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCrecimientoRouteImport } from './routes/_authenticated/crecimiento'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedFondoSeguridadRouteImport } from './routes/_authenticated/fondo-seguridad'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedRetiro50RouteImport } from './routes/_authenticated/retiro-50'
import { Route as AuthenticatedTradingJournalRouteImport } from './routes/_authenticated/trading-journal'
import { Route as AuthenticatedTradingLabRouteImport } from './routes/_authenticated/trading-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademiaRoute = AuthenticatedAcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrecimientoRoute =
  AuthenticatedCrecimientoRouteImport.update({
    id: '/crecimiento',
    path: '/crecimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFondoSeguridadRoute =
  AuthenticatedFondoSeguridadRouteImport.update({
    id: '/fondo-seguridad',
    path: '/fondo-seguridad',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetiro50Route = AuthenticatedRetiro50RouteImport.update({
  id: '/retiro-50',
  path: '/retiro-50',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradingJournalRoute =
  AuthenticatedTradingJournalRouteImport.update({
    id: '/trading-journal',
    path: '/trading-journal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradingLabRoute = AuthenticatedTradingLabRouteImport.update({
  id: '/trading-lab',
  path: '/trading-lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academia': typeof AuthenticatedAcademiaRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/crecimiento': typeof AuthenticatedCrecimientoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/fondo-seguridad': typeof AuthenticatedFondoSeguridadRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/retiro-50': typeof AuthenticatedRetiro50Route
  '/trading-journal': typeof AuthenticatedTradingJournalRoute
  '/trading-lab': typeof AuthenticatedTradingLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/academia': typeof AuthenticatedAcademiaRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/crecimiento': typeof AuthenticatedCrecimientoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/fondo-seguridad': typeof AuthenticatedFondoSeguridadRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/retiro-50': typeof AuthenticatedRetiro50Route
  '/trading-journal': typeof AuthenticatedTradingJournalRoute
  '/trading-lab': typeof AuthenticatedTradingLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/academia': typeof AuthenticatedAcademiaRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/crecimiento': typeof AuthenticatedCrecimientoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/fondo-seguridad': typeof AuthenticatedFondoSeguridadRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/retiro-50': typeof AuthenticatedRetiro50Route
  '/_authenticated/trading-journal': typeof AuthenticatedTradingJournalRoute
  '/_authenticated/trading-lab': typeof AuthenticatedTradingLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/academia'
    | '/configuracion'
    | '/crecimiento'
    | '/dashboard'
    | '/finanzas'
    | '/fondo-seguridad'
    | '/onboarding'
    | '/retiro-50'
    | '/trading-journal'
    | '/trading-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/academia'
    | '/configuracion'
    | '/crecimiento'
    | '/dashboard'
    | '/finanzas'
    | '/fondo-seguridad'
    | '/onboarding'
    | '/retiro-50'
    | '/trading-journal'
    | '/trading-lab'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/reset-password'
    | '/_authenticated/academia'
    | '/_authenticated/configuracion'
    | '/_authenticated/crecimiento'
    | '/_authenticated/dashboard'
    | '/_authenticated/finanzas'
    | '/_authenticated/fondo-seguridad'
    | '/_authenticated/onboarding'
    | '/_authenticated/retiro-50'
    | '/_authenticated/trading-journal'
    | '/_authenticated/trading-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academia': {
      id: '/_authenticated/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AuthenticatedAcademiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crecimiento': {
      id: '/_authenticated/crecimiento'
      path: '/crecimiento'
      fullPath: '/crecimiento'
      preLoaderRoute: typeof AuthenticatedCrecimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fondo-seguridad': {
      id: '/_authenticated/fondo-seguridad'
      path: '/fondo-seguridad'
      fullPath: '/fondo-seguridad'
      preLoaderRoute: typeof AuthenticatedFondoSeguridadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retiro-50': {
      id: '/_authenticated/retiro-50'
      path: '/retiro-50'
      fullPath: '/retiro-50'
      preLoaderRoute: typeof AuthenticatedRetiro50RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trading-journal': {
      id: '/_authenticated/trading-journal'
      path: '/trading-journal'
      fullPath: '/trading-journal'
      preLoaderRoute: typeof AuthenticatedTradingJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trading-lab': {
      id: '/_authenticated/trading-lab'
      path: '/trading-lab'
      fullPath: '/trading-lab'
      preLoaderRoute: typeof AuthenticatedTradingLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademiaRoute: typeof AuthenticatedAcademiaRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedCrecimientoRoute: typeof AuthenticatedCrecimientoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedFondoSeguridadRoute: typeof AuthenticatedFondoSeguridadRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRetiro50Route: typeof AuthenticatedRetiro50Route
  AuthenticatedTradingJournalRoute: typeof AuthenticatedTradingJournalRoute
  AuthenticatedTradingLabRoute: typeof AuthenticatedTradingLabRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademiaRoute: AuthenticatedAcademiaRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedCrecimientoRoute: AuthenticatedCrecimientoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedFondoSeguridadRoute: AuthenticatedFondoSeguridadRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRetiro50Route: AuthenticatedRetiro50Route,
  AuthenticatedTradingJournalRoute: AuthenticatedTradingJournalRoute,
  AuthenticatedTradingLabRoute: AuthenticatedTradingLabRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
